// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace CloudVeil.Mac
{
	public partial class SelfModerationViewController : NSViewController
	{
		public SelfModerationViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
